package dev.anhcraft.config;

import dev.anhcraft.config.adapter.TypeAdapter;
import dev.anhcraft.config.context.Context;
import dev.anhcraft.config.type.SimpleTypes;
import java.util.Set;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * The normalizer simplifies a complex object with the following rules:
 * <ul>
 *     <li>Primitive, primitive wrappers, String and {@link Dictionary} are returned as is, or deep-cloned if flag
 *     {@link SettingFlag.Normalizer#DEEP_CLONE} is set</li>
 *     <li>Array is recursively checked with each element normalized independently</li>
 *     <li>Common reference types are normalized using the built-in type adapters</li>
 * </ul>
 * For the rest of reference types, the normalizer tries to normalize them automatically using the schema generated by
 * the current {@link ConfigFactory}. Developers may use {@link TypeAdapter} to have further fine-grained control over
 * the normalization process. Failing to normalize an object will result in {@code null}.<br>
 * It is possible to hide certain data by specifying the superclass as the target type. This results in implicit
 * creation of the schema of the superclass. The result hides the details of the actual class and only contains the
 * information from the superclass up to the root of class hierarchy.
 * @see SimpleTypes#test(Object)
 * @see TypeAdapter
 */
public interface ConfigNormalizer {
  /**
   * Gets the setting flags.
   * @return the settings
   */
  @NotNull Set<SettingFlag.Normalizer> getSettings();

  /**
   * Normalizes the given complex object into a simple object.<br>
   * This creates a new {@link Context} to facilitate recursive calls.
   * @param complex the complex object
   * @return the simple object or {@code null} if the object cannot be normalized
   * @param <T> the type of the simple object
   * @see #normalize(Context, Class, Object)
   */
  <T> @Nullable Object normalize(@NotNull T complex);

  /**
   * Normalizes the given complex object into a simple object.
   * @param ctx the {@link Context} to use
   * @param complex the complex object
   * @return the simple object or {@code null} if the object cannot be normalized
   * @param <T> the type of the simple object
   * @see #normalize(Context, Class, Object)
   */
  <T> @Nullable Object normalize(@NotNull Context ctx, @NotNull T complex);

  /**
   * Normalizes the given complex object into a simple object.<br>
   * This normalizes {@code complex} using the schema of {@code type} and its superclasses. {@code <S>} can
   * be bounded to a certain supertype of {@code <T>} to make the simple object more generic. However, this
   * only works for the first step of transformation.
   * @param ctx the {@link Context} to use
   * @param type the class or superclass of the complex object
   * @param complex the complex object
   * @return the simple object or {@code null} if the object cannot be normalized
   * @param <S> the type or supertype of the complex object
   * @param <T> the type of the simple object
   */
  <S, T extends S> @Nullable Object normalize(
      @NotNull Context ctx, @NotNull Class<S> type, @NotNull T complex);

  /**
   * Normalizes the given complex object into the given dictionary.<br>
   * This creates a new {@link Context} to facilitate recursive calls.
   * @param complex the complex object
   * @param dictionary the dictionary
   * @param <T> the type of the complex object
   * @see #normalize(Context, Class, Object)
   */
  <T> void normalizeToDictionary(@NotNull T complex, @NotNull Dictionary dictionary);

  /**
   * Normalizes the given complex object into the given dictionary.
   * @param ctx the {@link Context} to use
   * @param complex the complex object
   * @param dictionary the dictionary
   * @param <T> the type of the complex object
   * @see #normalize(Context, Class, Object)
   */
  <T> void normalizeToDictionary(
      @NotNull Context ctx, @NotNull T complex, @NotNull Dictionary dictionary);

  /**
   * Normalizes the given complex object into the given dictionary.<br>
   * This normalizes {@code complex} using the schema of {@code type} and its superclasses. {@code <S>} can
   * be bounded to a certain supertype of {@code <T>} to make the simple object more generic. However, this
   * only works for the first step of transformation.
   * @param ctx the {@link Context} to use
   * @param type the class or superclass of the complex object
   * @param complex the complex object
   * @param dictionary the dictionary
   * @param <S> the type or supertype of the complex object
   * @param <T> the type of the complex object
   * @see #normalize(Context, Class, Object)
   */
  <S, T extends S> void normalizeToDictionary(
      @NotNull Context ctx,
      @NotNull Class<S> type,
      @NotNull T complex,
      @NotNull Dictionary dictionary);
}
