package dev.anhcraft.config;

import dev.anhcraft.config.adapter.TypeAdapter;
import dev.anhcraft.config.context.Context;
import dev.anhcraft.config.type.TypeToken;
import java.lang.reflect.Type;
import java.util.Set;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * The denormalizer complexifies a simple object with the following rules:
 * <ul>
 *     <li>Primitive and String are transformed using the built-in type adapters (*)</li>
 *     <li>Array is recursively checked with each element denormalized independently</li>
 *     <li>Dictionary is denormalized into a new instance of the target type</li>
 * </ul>
 * The denormalizer may return {@code null} even if the target type is primitive.<br>
 * Developers may use {@link TypeAdapter} to have further fine-grained control over the denormalization process. If such
 * adapter is not found, the denormalizer tries to denormalize the object using the schema generated by the current
 * {@link ConfigFactory} with the prerequisite is that the source setting must be a dictionary. Failing to denormalize
 * an object will result in {@code null} or implicit skip.<br>
 * When denormalizing a dictionary without type adapter into an instance of a parameterized type, it is important to
 * provide fully-informed actual type using {@link TypeToken} so that parameterized types of fields can be resolved
 * recursively, which results in a complete denormalization.<br>
 * It is possible to hide certain data by specifying the superclass as the target type. This results in implicit
 * creation of the schema of the superclass. The result hides the details of the actual class and only contains the
 * information from the superclass up to the root of class hierarchy.
 * @see TypeAdapter
 * @see TypeToken
 */
public interface ConfigDenormalizer {
  /**
   * Gets the setting flags.
   * @return the settings
   */
  @NotNull Set<SettingFlag.Denormalizer> getSettings();

  /**
   * Denormalizes the given simple object into a complex object.<br>
   * This creates a new {@link Context} to facilitate recursive calls.
   * @param simple the simple object
   * @param targetType the target complex type
   * @return the complex object or {@code null} if the object cannot be denormalized
   * @param <T> the type of the simple object
   * @see #denormalize(Context, Object, Type)
   */
  <T> @Nullable Object denormalize(@Nullable T simple, @NotNull Type targetType);

  /**
   * Denormalizes the given simple object into a complex object.
   * @param ctx the {@link Context} to use
   * @param simple the simple object
   * @param targetType the target complex type
   * @return the complex object or {@code null} if the object cannot be denormalized
   * @param <T> the type of the simple object
   */
  <T> @Nullable Object denormalize(
      @NotNull Context ctx, @Nullable T simple, @NotNull Type targetType);

  /**
   * Denormalizes the given dictionary into the given instance.<br>
   * This creates a new {@link Context} to facilitate recursive calls.
   * @param simple the dictionary
   * @param targetType the target complex type
   * @param instance the instance
   */
  void denormalizeToInstance(
      @NotNull Dictionary simple, @NotNull Type targetType, @NotNull Object instance);

  /**
   * Denormalizes the given dictionary into the given instance.
   * @param ctx the {@link Context} to use
   * @param simple the dictionary
   * @param targetType the target complex type
   * @param instance the instance
   */
  void denormalizeToInstance(
      @NotNull Context ctx,
      @NotNull Dictionary simple,
      @NotNull Type targetType,
      @NotNull Object instance);
}
